version: 2

jobs:
  build:
    docker:
      - image: cimg/php:8.1.0
        environment:
          APP_ENV: testing
          DB_CONNECTION: mysql_test
          DB_HOST: 127.0.0.1
          DB_DATABASE: resepj_test
          DB_USERNAME: root
          DB_PASSWORD: root
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: resepj_test
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd
    working_directory: ~/ci-demo

    steps:
      - checkout

      - run:
      # プライマリコンテナは MYSQL ではないので、準備ができるまでスリープコマンドを実行します。
          name: MySQL が準備できるまで待機
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1

      - run: sudo apt update

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run: ./vendor/bin/phpunit
