version: 2

jobs:
  build:
    docker:
      - image: cimg/php:8.1.0
        environment:
          APP_DEBUG: true
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_DATABASE: resepj_test
          DB_USERNAME: 'root'
          DB_PASSWORD: ''
      - image: cimg/mysql:8.0
        environment:
          MYSQL_DATABASE: testing
          MYSQL_ROOT_HOST: '%'
          MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          TZ: Asia/Tokyo
    working_directory: ~/ci-demo

    steps:
      - checkout

      - run: sudo apt update

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run: ./vendor/bin/phpunit
